### PR TITLE
chore: Convert tests to compare row objects vs string from Tableau format

### PR DESCRIPTION
**Pull request by bbejeck**

### CODE REVIEW

**Comment by bbejeck** [comment]
The `FlinkSqlFindingDistinctWindowedTest` is hanging currently - maybe I need to apply the same fix you applied for the pattern matching?

**Comment by davetroiano** [comment]
> The `FlinkSqlFindingDistinctWindowedTest` is hanging currently - maybe I need to apply the same fix you applied for the pattern matching?

yeah I took a quick look and it's hanging at the same exact spot. if you rebase on master and change to:
```
List<Row> actualResults = rowObjectsFromTableResult(tableResult, 4);
```
that should get past it

**Review by davetroiano — COMMENTED** [review]
LGTM, just need the workaround for `FlinkSqlFindingDistinctWindowedTest`

**Comment by bbejeck** [comment]
@davetroiano changes applied and the test is passing now

**Review by davetroiano — APPROVED** [review]
LGTM!

**Pull request merged**
